# Generated by Django 3.2.8 on 2021-10-14 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('date_published', models.DateField()),
                ('min_duration', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('production_company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('avg_vote', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=50)),
                ('genre', models.CharField(choices=[('action', 'action'), ('adult', 'adult'), ('adventure', 'adventure'), ('animation', 'animation'), ('biography', 'biography'), ('comedy', 'comedy'), ('crime', 'crime'), ('documentary', 'documentary'), ('drama', 'drama'), ('family', 'family'), ('fantasy', 'fantasy'), ('history', 'history'), ('horror', 'horror'), ('musical', 'musical'), ('mystery', 'mystery'), ('romance', 'romance'), ('war', 'war')], max_length=55)),
            ],
        ),
    ]
