# Generated by Django 3.2.8 on 2021-10-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_auto_20211014_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='genre',
            field=models.CharField(choices=[('action', 'action'), ('adult', 'adult'), ('adventure', 'adventure'), ('animation', 'animation'), ('biography', 'biography'), ('comedy', 'comedy'), ('crime', 'crime'), ('documentary', 'documentary'), ('drama', 'drama'), ('family', 'family'), ('fantasy', 'fantasy'), ('history', 'history'), ('horror', 'horror'), ('musical', 'musical'), ('mystery', 'mystery'), ('romance', 'romance'), ('sci-fi', 'sci-fi'), ('thriller', 'thriller'), ('war', 'war')], max_length=55),
        ),
    ]
